# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - main

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: Deployment/build-app.yml

  - stage: Tests
    dependsOn: Build
    jobs:
      - job: Tests
        steps:
          - template: Deployment/test-app.yml

  - stage: PublishInternal
    dependsOn: Tests
    condition: |
      and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'), 
                       ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: PublishInternal
        steps:
          - template: Deployment/push-internal.yml

  - stage: PublishNuget
    dependsOn: Tests
    condition: and(succeeded(),ne(variables['Build.Reason'], 'PullRequest'),
      eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - job: PublishNuget
        steps:
          - template: Deployment/push-nugetorg.yml
